export enum AccountStatus {
    ACTIVE = 'ACTIVE',
    NOT_ACTIVE = 'NOT_ACTIVE',
    COMPLETE_REGISTRATION_REQUIRED = 'COMPLETE_REGISTRATION_REQUIRED',
    BLOCKED = 'BLOCKED',
    DELETED = 'DELETED'
}
